// web-ui/src/pages/LoginPage.vue
<template>
  <section class="login-page">
    <el-card class="login-card" shadow="never">
      <template #header>
        <div class="login-card__header">
          <h1>登录控制台</h1>
          <p>使用管理员账号进入饥荒管理控制台</p>
        </div>
      </template>

      <el-alert
        v-if="errorMessage"
        :title="errorMessage"
        type="error"
        show-icon
        :closable="false"
      />

      <el-form class="login-form" label-position="top" @submit.prevent="handleSubmit">
        <el-form-item label="用户名">
          <el-input v-model="form.username" autocomplete="username" placeholder="请输入用户名" />
        </el-form-item>

        <el-form-item label="密码">
          <el-input
            v-model="form.password"
            autocomplete="current-password"
            placeholder="请输入密码"
            show-password
            type="password"
          />
        </el-form-item>

        <el-button
          class="login-form__submit"
          :loading="auth.loading || submitting"
          native-type="submit"
          type="primary"
        >
          登录
        </el-button>
      </el-form>
    </el-card>
  </section>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'

import { normalizeApiError } from '@/shared/api/http'
import { routes } from '@/shared/config/routes'
import { useAuthStore } from '@/shared/stores/auth'
import type { LoginRequest } from '@/shared/types/domain'

const auth = useAuthStore()
const route = useRoute()
const router = useRouter()

const form = reactive<LoginRequest>({
  username: '',
  password: '',
})
const submitting = ref(false)
const errorMessage = ref('')
const redirectTarget = computed(() => {
  const redirect = route.query.redirect
  return typeof redirect === 'string' && redirect ? redirect : routes.panel
})

async function handleSubmit(): Promise<void> {
  errorMessage.value = ''
  submitting.value = true

  try {
    await auth.loginWithPassword(form)
    await router.replace(redirectTarget.value)
  } catch (error) {
    errorMessage.value = normalizeApiError(error).message
  } finally {
    submitting.value = false
  }
}
</script>

<style scoped>
.login-page {
  width: min(420px, 100%);
}

.login-card {
  border: 1px solid #d7dee9;
  border-radius: 8px;
}

.login-card__header {
  display: grid;
  gap: 6px;
}

.login-card__header h1,
.login-card__header p {
  margin: 0;
}

.login-card__header h1 {
  font-size: 22px;
  line-height: 1.25;
}

.login-card__header p {
  color: #667085;
  font-size: 14px;
}

.login-form {
  display: grid;
  gap: 2px;
  margin-top: 14px;
}

.login-form__submit {
  width: 100%;
  margin-top: 4px;
}
</style>

// web-ui/src/pages/LoginPage.tsx
import { ProCard } from '@ant-design/pro-components'
import { App as AntApp, Button, Form, Input } from 'antd'
import { useNavigate } from 'react-router'

import { login, type LoginPayload } from '@/features/auth/auth.api'
import { markAuthenticated } from '@/features/auth/auth-state'
import { assertApiSuccess, getErrorMessage } from '@/shared/api/envelope'
import { routes } from '@/shared/config/routes'

export default function LoginPage() {
  const navigate = useNavigate()
  const { message } = AntApp.useApp()

  return (
    <ProCard className="auth-card" title="登录" bordered={false}>
      <Form
        layout="vertical"
        onFinish={async (values: LoginPayload) => {
          try {
            assertApiSuccess(await login(values))
            markAuthenticated()
            navigate(routes.panel, { replace: true })
          } catch (error) {
            message.error(getErrorMessage(error, '登录失败'))
          }
        }}
      >
        <Form.Item
          label="用户名"
          name="username"
          rules={[{ required: true, message: '请输入用户名' }]}
        >
          <Input placeholder="请输入用户名" />
        </Form.Item>
        <Form.Item label="密码" name="password" rules={[{ required: true, message: '请输入密码' }]}>
          <Input.Password placeholder="请输入密码" />
        </Form.Item>
        <Button type="primary" htmlType="submit" block>
          登录
        </Button>
      </Form>
    </ProCard>
  )
}
