// web-ui/src/pages/SettingsPage.vue
<template>
  <PageState title="设置" description="管理 DST 服务端路径、集群存储和运行参数。">
    <el-card shadow="never">
      <template #header>
        <div class="section-header">
          <span>DST 配置</span>
          <el-button :icon="Refresh" :loading="loading" size="small" @click="loadSettings">
            重新加载
          </el-button>
        </div>
      </template>

      <el-alert
        class="settings-alert"
        :closable="false"
        show-icon
        title="此页保存 DST 服务端路径、集群存储和运行参数到后端 dst_config 文件。"
        type="info"
      />

      <el-form v-loading="loading" label-position="top" @submit.prevent>
        <section class="settings-section">
          <h2>服务端路径</h2>
          <el-row :gutter="12">
            <el-col :xs="24" :lg="8">
              <el-form-item label="SteamCMD 目录">
                <div class="field-control" data-test="steamcmd-input">
                  <el-input v-model="form.steamcmd" placeholder="/opt/steamcmd" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="游戏安装目录">
                <div class="field-control" data-test="force-install-dir-input">
                  <el-input v-model="form.force_install_dir" placeholder="/opt/dst-server" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="饥荒服务端目录">
                <div class="field-control" data-test="donot-starve-server-directory-input">
                  <el-input v-model="form.donot_starve_server_directory" placeholder="可留空" />
                </div>
              </el-form-item>
            </el-col>
          </el-row>
        </section>

        <section class="settings-section">
          <h2>集群与存储</h2>
          <el-row :gutter="12">
            <el-col :xs="24" :lg="8">
              <el-form-item label="集群名称">
                <div class="field-control" data-test="cluster-input">
                  <el-input v-model="form.cluster" placeholder="Cluster_1" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="备份目录">
                <div class="field-control" data-test="backup-input">
                  <el-input v-model="form.backup" placeholder="/opt/dst-backup" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="模组下载目录">
                <div class="field-control" data-test="mod-download-path-input">
                  <el-input v-model="form.mod_download_path" placeholder="/opt/dst-mods" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="持久化根目录">
                <div class="field-control" data-test="persistent-storage-root-input">
                  <el-input v-model="form.persistent_storage_root" placeholder="可留空" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="配置目录名">
                <div class="field-control" data-test="conf-dir-input">
                  <el-input v-model="form.conf_dir" placeholder="DoNotStarveTogether" />
                </div>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="UGC 目录">
                <div class="field-control" data-test="ugc-directory-input">
                  <el-input v-model="form.ugc_directory" placeholder="可留空" />
                </div>
              </el-form-item>
            </el-col>
          </el-row>
        </section>

        <section class="settings-section">
          <h2>运行参数</h2>
          <el-row :gutter="12">
            <el-col :xs="24" :lg="8">
              <el-form-item label="运行位数">
                <el-radio-group v-model="form.bin" data-test="bin-radio-group">
                  <el-radio-button :value="32">32 位</el-radio-button>
                  <el-radio-button :value="64">64 位</el-radio-button>
                </el-radio-group>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :lg="8">
              <el-form-item label="测试分支">
                <el-radio-group v-model="form.beta" data-test="beta-radio-group">
                  <el-radio-button :value="0">关闭</el-radio-button>
                  <el-radio-button :value="1">开启</el-radio-button>
                </el-radio-group>
              </el-form-item>
            </el-col>
          </el-row>
        </section>

        <el-form-item>
          <el-button :icon="Check" :loading="saving" type="primary" @click="handleSave">
            保存设置
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </PageState>
</template>

<script setup lang="ts">
import { Check, Refresh } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { onMounted, reactive, ref } from 'vue'

import { getDstConfig, saveDstConfig, type DstConfig } from '@/features/settings/settings.api'
import {
  createEmptyDstConfig,
  normalizeDstConfig,
  prepareDstConfigForSave,
  validateDstConfig,
} from '@/features/settings/settings-form'
import { assertApiSuccess, getErrorMessage, readApiData } from '@/shared/api/envelope'
import PageState from '@/shared/components/PageState.vue'

const form = reactive<DstConfig>(createEmptyDstConfig())
const loading = ref(false)
const saving = ref(false)

onMounted(() => {
  void loadSettings()
})

async function loadSettings(): Promise<void> {
  loading.value = true

  try {
    Object.assign(form, normalizeDstConfig(readApiData(await getDstConfig(), '设置加载失败')))
  } catch (error) {
    ElMessage.error(getErrorMessage(error, '设置加载失败'))
  } finally {
    loading.value = false
  }
}

async function handleSave(): Promise<void> {
  const payload = prepareDstConfigForSave(form)
  const validationError = validateDstConfig(payload)

  if (validationError) {
    ElMessage.error(validationError)
    return
  }

  saving.value = true

  try {
    assertApiSuccess(await saveDstConfig(payload))
    await loadSettings()
    ElMessage.success('设置已保存')
  } catch (error) {
    ElMessage.error(getErrorMessage(error, '设置保存失败'))
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.settings-alert {
  margin-bottom: 16px;
}

.settings-section {
  margin-bottom: 8px;
}

.settings-section h2 {
  margin: 0 0 12px;
  font-size: 16px;
  font-weight: 600;
}

.field-control {
  width: 100%;
}
</style>

// web-ui/src/pages/SettingsPage.tsx
import { ProCard } from '@ant-design/pro-components'
import { App as AntApp, Button, Form, Input, Radio, Spin } from 'antd'
import { SaveOutlined } from '@ant-design/icons'
import { useEffect, useState } from 'react'

import { getDstConfig, saveDstConfig } from '@/features/settings/settings.api'
import {
  normalizeDstConfig,
  serializeDstConfig,
  validateDstConfig,
} from '@/features/settings/settings-form'
import { assertApiSuccess, getErrorMessage } from '@/shared/api/envelope'
import type { DstConfig } from '@/shared/types/domain'

export default function SettingsPage() {
  const { message } = AntApp.useApp()
  const [form] = Form.useForm<DstConfig>()
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    let ignore = false

    async function loadConfig() {
      try {
        setLoading(true)
        const config = normalizeDstConfig(assertApiSuccess(await getDstConfig()))
        if (!ignore) {
          form.setFieldsValue(config)
        }
      } catch (error) {
        message.error(getErrorMessage(error, '加载系统设置失败'))
      } finally {
        if (!ignore) {
          setLoading(false)
        }
      }
    }

    void loadConfig()
    return () => {
      ignore = true
    }
  }, [form, message])

  async function handleSave(values: DstConfig) {
    const nextValues = normalizeDstConfig(values)
    const invalidFields = validateDstConfig(nextValues)
    if (invalidFields.length > 0) {
      message.warning(`请填写必填项: ${invalidFields.join(', ')}`)
      return
    }

    try {
      setSaving(true)
      assertApiSuccess(await saveDstConfig(serializeDstConfig(nextValues)))
      message.success('系统设置已保存')
    } catch (error) {
      message.error(getErrorMessage(error, '保存系统设置失败'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <ProCard title="系统设置" className="settings-page-card" bordered={false}>
      {loading ? (
        <div className="page-loading">
          <Spin />
        </div>
      ) : (
        <Form form={form} layout="vertical" className="settings-form" onFinish={handleSave}>
          <section>
            <h3>基础路径</h3>
            <Form.Item label="SteamCMD" name="steamcmd" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
            <Form.Item label="游戏安装目录" name="force_install_dir" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
            <Form.Item label="备份目录" name="backup" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
            <Form.Item label="模组下载目录" name="mod_download_path" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
          </section>
          <section>
            <h3>Klei 配置</h3>
            <Form.Item label="集群目录" name="cluster" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
            <Form.Item label="持久化根目录" name="persistent_storage_root">
              <Input />
            </Form.Item>
            <Form.Item label="配置目录名" name="conf_dir">
              <Input />
            </Form.Item>
            <Form.Item label="UGC 目录" name="ugc_directory">
              <Input />
            </Form.Item>
          </section>
          <section>
            <h3>运行参数</h3>
            <Form.Item label="服务端目录名" name="donot_starve_server_directory">
              <Input />
            </Form.Item>
            <Form.Item label="运行架构" name="bin">
              <Radio.Group
                options={[
                  { label: '32 位', value: '32' },
                  { label: '64 位', value: '64' },
                ]}
              />
            </Form.Item>
            <Form.Item label="测试分支" name="beta">
              <Radio.Group
                options={[
                  { label: '关闭', value: 0 },
                  { label: '开启', value: 1 },
                ]}
              />
            </Form.Item>
          </section>
          <div className="settings-save-bar">
            <Button type="primary" htmlType="submit" icon={<SaveOutlined />} loading={saving}>
              保存设置
            </Button>
          </div>
        </Form>
      )}
    </ProCard>
  )
}
